language: python
branches:
  only:
    - 4.1-robot
python:
  - 2.6
install:
  - python bootstrap.py -c pybot.cfg
  - bin/buildout -q -t 5 -c pybot.cfg
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - bin/instance start
  - sleep 5
script:
  - bin/pybot acceptance-tests
after_script:
  - bin/instance stop